name: Deploy

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "21"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Preparando artefato
              run: |
                mkdir -p artifact
                cp -r ./build/* ./artifact/
      
            - name: Salvando artefato
              uses: actions/upload-artifact@v3
              with:
                name: audittei-front
                path: artifact

    deploy-staging:
        runs-on: ubuntu-latest
        environment:
            name: Staging
            url: http://auditteifront.ofernandoavila.com
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: audittei-front
                path: ./artifact
            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                REMOTE_USER: ${{ vars.REMOTE_USER }}
                SOURCE: "audittei-front/"
                TARGET: ${{ vars.TARGET }}
