name: Deploy

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "21"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
    deploy-staging:
        runs-on: ubuntu-latest
        environment:
            name: Staging
            url: http://auditteifront.ofernandoavila.com
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: "-rlgoDzvc --delete"
                  SOURCE: "/build"
                  REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                  REMOTE_USER: ${{ vars.REMOTE_USER }}
                  REMOTE_PORT: ${{ vars.REMOTE_PORT }}
                  TARGET: ${{ vars.TARGET }}
