name: Deploy

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "21"

            - name: Install dependencies
              run: npm install

            - name: Create .env file
              run: |
                echo "REACT_APP_GOOGLE_ANALYTICS=${{ secrets.GOOGLE_ANALYTICS }}" > .env

            - name: Build
              run: npm run build

            - name: Adicionando htaccess ao bundle
              run: |
                cp .htaccess ./build/.htaccess

            - name: Preparando artefato
              run: |
                mkdir -p artifact
                cp -r ./build/* ./artifact/
      
            - name: Salvando artefato
              uses: actions/upload-artifact@v4
              with:
                name: audittei-front
                path: artifact

    HML:
        runs-on: ubuntu-latest
        environment:
            name: Staging
            url: ${{ vars.BASE_URL }}
        needs: Build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: audittei-front
                path: ./artifact
            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                ARGS: "-rlgoDzvc --delete"
                REMOTE_HOST: ${{ vars.REMOTE_HOST }}
                REMOTE_USER: ${{ vars.REMOTE_USER }}
                SOURCE: "artifact/"
                TARGET: ${{ vars.TARGET }}

    PRD:
        runs-on: ubuntu-latest
        environment:
            name: Production
            url: ${{ vars.BASE_URL }}
        needs: HML
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: audittei-front
                path: ./artifact
            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: ${{ vars.FTP_HOST }}
                username: ${{ vars.FTP_USER }}
                password: ${{ secrets.FTP_PASSWORD }}
                local-dir: artifact/
                server-dir: public_html/
